version:  '3'
services:

  signalserver:
    build: .
    restart: always
    ports: 
      - 8080:8080
    networks:
      - client-side

  redis:
    image: redis:latest
    container_name: signal-server_redis
    restart: always
    ports:
      - 6379:6379

  postgresql_accountdb:
    image: postgres:latest
    container_name: signal-server_accountdb
    restart: always
    volumes:
      - ./postgresql/accountdb.sql:/docker-entrypoint-initdb.d/accountdb.sql
      - ./postgresql/accountdb:/var/lib/postgresql/data/
    ports:
      - 5421:5432
    environment:
      - POSTGRES_USER=signal-server
      - POSTGRES_PASSWORD=signalsecretpassword
      - POSTGRES_DB=accountdb

  postgresql_messagedb:
    image: postgres:latest
    container_name: signal-server_messagedb
    restart: always
    volumes:
      - ./postgresql/messagedb.sql:/docker-entrypoint-initdb.d/messagedb.sql
      - ./postgresql/messagedb:/var/lib/postgresql/data/
    ports:
      - 5422:5432
    environment:
      - POSTGRES_USER=signal-server
      - POSTGRES_PASSWORD=signalsecretpassword
      - POSTGRES_DB=messagedb

networks:
  client-side: {}
  server-side: {}