version:  '3'
services:

  signalserver:
    build: ./build.sh
    container_name: signal-server
    restart: always
    ports: 
      - "8080:8080"

  redis:
    image: redis:latest
    container_name: signal-server_redis
    restart: always
    ports:
      - "6379:6379"